//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test01api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wash
    {
        public int ID { get; set; }
        public int IDNumberOfMachine { get; set; }
        public int IDPowder { get; set; }
        public int IDDrying { get; set; }
        public int IDUser { get; set; }
        public int IDStatusOfWash { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Drying Drying { get; set; }
        public virtual Powder Powder { get; set; }
        public virtual StatusOfWash StatusOfWash { get; set; }
        public virtual User User { get; set; }
        public virtual WashMachine WashMachine { get; set; }
    }
}
